### PR TITLE
Update meta.yaml

### PR DESCRIPTION
**Pull request by ymontmarin**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by ymontmarin** [comment]
@conda-forge-admin, please rerender

**Comment by ymontmarin** [comment]
@conda-forge-admin, please rerender

**Comment by jcarpent** [comment]
@ymontmarin You should wait the dependencies to be updated first, like OSG

**Comment by ymontmarin** [comment]
@jcarpent Indeed, I waited for `osg-qt` to finish its CI before doing the commits you commented. It was the dependency blocking this PR needed for HPP stack re-release. The OSG PR is kind of // and not needed for this re-release, it is mostly about enabling conda to move forward with ffmpeg migration, but the actual built package will not change.

**Comment by jcarpent** [comment]
But is is better to do step by step in the hierarchy of dependencies. Otherwise, you will be stuck with outdated binaries!

**Pull request merged**
